### ISSUE TITLE
OBSOLETE: use of center tags

### ISSUE THREAD

**Issue by phun-ky** [storebrand/storebrand.ny#10]
In the new notification boxes, you have used `center`-tags, and those tags are depreacted/obsolete!

REF: http://www.w3.org/TR/html5/obsolete.html under 

## 11.2 Non-conforming features

>Elements in the following list are entirely obsolete, and must not be used by authors:

Please use html5 standards

**Comment by stbbzt** [comment]
Should be fixed now, including by the use of the Bootstrap class text-center.
