### ISSUE TITLE
REQUEST: Separate google analytics tagging in a frontend module

### ISSUE THREAD

**Issue by phun-ky** [storebrand/storebrand.ny#13]
_This can wait until Håvard Hvassing and BZT/business have decided what to do with GA vs GTM_

    $('button').bind( "click", function() {
      var btnTxt = $(this).html();
      var path = window.location.pathname;
      //console.log(btnTxt);
      //console.log(page);
      ga('send', 'event', path , 'Klikk på knappen', btnTxt);
    });

    $('.mini.clickable').bind( "click", function() {
      var boxId = $(this).attr('alt');
      var path = window.location.pathname;
      //console.log(boxId);
      //console.log(path);
      ga('send', 'event', path , 'Klikk på boksen ', boxId);
    });

    $('.twister').bind( "click", function() {
      console.log('faq');
      var q = $(this).html();
      var path = window.location.pathname;
      //console.log(q);
      //console.log(path);
      ga('send', 'event', path , 'Klikk på boksen ', q);
    });

this should be in a separate fronten module, and arranged accordingly to the choice of tagging used (GA or GTM)

**Comment by stbbzt** [comment]
Handled.
