### ISSUE TITLE
REQUEST: Add a css class to check for, to asynchronously load stb-main.css if it's not present

### ISSUE THREAD

**Issue by phun-ky** [storebrand/storebrand.ny#18]
Could you add something like:

    .stbny-stylecheck{
      z-index:1337;
    }

in the stb-main.css, so I can create an element to check if the CSS is loaded, and then load stb-main.css if it is not loaded?

**Comment by stbbzt** [comment]
The last few bytes of stb-all.min.css now read: 

.storebrand-stylecheck{z-index:42}

Nice to have.
