### ISSUE TITLE
CRLF linefeeds, boo!

### ISSUE THREAD

**Issue by nilsel** [storebrand/storebrand.ny#22]
This generates a lot of noise for other platforms than windows, please set your editors to use LF-only as line separators (unix style) :). As of now we have a mix of line-endings in different files.
> warning: CRLF will be replaced by LF in less/stb-color-variables.less.                                                                
> The file will have its original line endings in your working directory.
(this happens on a lot of files)

This should be done in a separate commit, maybe using "find . -name '*.less' | xargs dos2unix" (command not tested, just how I remembered it).

**Comment by stbbzt** [comment]
Not really an issue with storebrand.ny, but people should listen. 

For Sublime Text 3, see https://blog.hostonnet.com/how-to-set-unix-as-default-line-ending-in-sublime-text .
