### ISSUE TITLE
Assets not gzipped

### ISSUE THREAD

**Issue by nilsel** [storebrand/storebrand.ny#24]
Example URL: https://elements.storebrand.no/storebrand.ny/0.77/css/stb-main.css

Response is not gzipped, we could save quite a lot of traffic serving these assets gzipped. Amazon S3 does not itself support this, but it can be accomplished manually, see: http://www.rightbrainnetworks.com/blog/serving-compressed-gzipped-static-files-from-amazon-s3-or-cloudfront/

**Comment by stbbzt** [comment]
I'll be happy to see someone create an automated grunt step on Windows for this ... ;)

**Comment by nilsel** [comment]
I think it's worth the effort: the CSS is 214kb, with gzip it's (reportedly) reduced to 34kb. That's a big win :)

**Comment by nilsel** [comment]
Leaving this link here for reference: https://github.com/gruntjs/grunt-contrib-compress

**Comment by nilsel** [comment]
Fixed in pull-req. Shaved off total 463 kb for js+css. ~1.5sec to 0.5sec - gzip FTW :zap:
