### ISSUE TITLE
YouTube js-code loads on all pages

### ISSUE THREAD

**Issue by nilsel** [storebrand/storebrand.ny#26]
Currently the stb-video.js file is embedded into stb-all.min.js. This triggers requests to youtube, and creates some kind of iframe :ghost:  IMHO we should include this only on pages that actually uses video. We're wasting 8.9kb and two browser-requests on every pageload at the moment.

**Comment by nilsel** [comment]
On my wishlist:
Some server-side tech that takes request-params and serves back a minified (gzipped :) ) version.
For example:
GET /api/js/bundle/#stb-ny,youtube,analytics,bootstrap

Kinda like running gulp/grunt on the server, but with smart caching and stuff™.

**Comment by nilsel** [comment]
One fix could be to add a check in the stb-video.js:
If there is any video-elements in the DOM (or placeholders), run the script. If not, "return" immediately. :)

**Comment by stbbzt** [comment]
I think we'll go for the easy fix; run code, but escape before iframe creation if there's no video element on the page. I'll add a Jira issue about it, but I'm guessing this may not be in production before we do a somewhat thorough web manual make-over.

**Comment by stbbzt** [comment]
This will be fixed in v0.89 of the Web manual, implemented as described on 2015-10-09. 
Almost two lines of code, so this took a while.
