### ISSUE TITLE
Switch to Zopfli compression?

### ISSUE THREAD

**Issue by nilsel** [storebrand/storebrand.ny#31]
Zopfli is a gzip-compatible alternative, I'll test it out on our assets and post a comparison if noone else does it before me :)
http://blog.codinghorror.com/zopfli-optimization-literally-free-bandwidth/

**Comment by stbbzt** [comment]
As long as Amazon handles the compression for us, we might as well just use whatever they use, and not think more about it. No?

**Comment by nilsel** [comment]
yep.. and IF we implement zopfli amazon will probably add it to cloudFront a few weeks later anyway ;)

quick comparison with gzip level 9, and 1000 iterations for zopfli, I'm not that impressed.

JS:
- gzip -9: 103kb
- zopfli (w/1000 iterations): 100kb
- minified: 349kb

CSS:
- gzip -9: 38kb
- zopfli: 36kb
- minified: 244kb
