### ISSUE TITLE
Class: ...visual  should be "...visuals"

### ISSUE THREAD

**Issue by ehsantoucerkany** [storebrand/storebrand.ny#48]
On https://elements.storebrand.no/storebrand.ny/1.0.8/webmanual.html#

![skarmavbild 2017-08-23 kl 10 57 22](https://user-images.githubusercontent.com/604690/29607578-ee04f3f2-87f1-11e7-9b6f-bdee454303af.png)

**Comment by nilsel** [comment]
Will be out in 1.0.11
