### ISSUE TITLE
REQUEST: Provide a dist build for consuming apps

### ISSUE THREAD

**Issue by kschulst** [storebrand/storebrand.ny#6]
Provide a /dist with compiled css and the required assets.

Maybe this could be achieved by a hook whenever someone pushes?

Background: I want to be able to grab storebrand.ny using bower and then be getting the minimal of what to include in my app in order to use the new designs.

**Comment by nilsel** [comment]
If you need ready-to-go minified/gzipped css/js one can just use the Amazon CDN links provided in the webmanual.
